/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -m -c DBusMenuInterface -i src/libdbusmenuqt/dbusmenutypes_p.h -p dbusmenu_interface /home/reion/Cute/statusbar/src/libdbusmenuqt/com.canonical.dbusmenu.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusmenu_interface.h"

/*
 * Implementation of interface class DBusMenuInterface
 */

DBusMenuInterface::DBusMenuInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DBusMenuInterface::~DBusMenuInterface()
{
}
